BUGFIX: Non-lazy injection of Doctrine EntityManager
In the Doctrine\PersistenceManager the Doctrine EntityManager is
injected. That needs to be done non-lazily. Probably not a problem
in real life, and not even when running all functional tests, but
when running e.g. just the Functional\Mvc\ActionControllerTest this
lead to:

    TypeError: Argument 1 passed to …\SchemaTool::__construct() must
    be an instance of Doctrine\ORM\EntityManagerInterface, instance of
    Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy given